### PR TITLE
screenshot for metadata and Dutch metadata

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by hzak** [comment]
@PanderMusubi I've updated the descriptions, can you please review them?

**Comment by PanderMusubi** [comment]
Will do in two days and let you know. Thanks for the heads up.

**Comment by PanderMusubi** [comment]
@hzak done

**Comment by hzak** [comment]
@PanderMusubi also for the short description and title we suggest the following:
short description: `Mobile wallet for the cryptocurrency Firo.`
title: `Firo`

**Comment by PanderMusubi** [comment]
Done

**Pull request merged**
